openapi: 3.1.0
info:
  title: http://orders.sock-shop
  description: Mizu observed 2924005 entries (324640 failed), at 0.473 hits/s, average
    response time is 0.032 seconds
  version: '1.0'
servers:
- url: http://orders.sock-shop
paths:
  "/orders":
    post:
      tags:
      - orders
      summary: "/orders"
      description: Mizu observed 2923993 entries (324640 failed), at 0.473 hits/s,
        average response time is 0.031 seconds
      operationId: ba3f307a-1c68-402c-a4d7-8af9fdbd5f33
      responses:
        '201':
          description: Successful call with status 201
          content:
            application/json:
              example:
                address:
                  city: Glasgow
                  country: United Kingdom
                  id:
                  number: '246'
                  postcode: G67 3DL
                  street: Whitelees Road
                card:
                  ccv: '958'
                  expires: '08/19'
                  id:
                  longNum: '5544154011345918'
                customer:
                  addresses: []
                  cards: []
                  firstName: User
                  id:
                  lastName: Name
                  username: user
                customerId: 57a98d98e4b00679b4a830b2
                date: '2022-06-19T07:42:41.828+0000'
                id: 62aed37161c4e9000733c011
                items:
                - id: 62aed37176ea610008ced921
                  itemId: 819e1fbf-8b7e-4f6d-811f-693534916a8b
                  quantity: 1
                  unitPrice: 14
                shipment:
                  id: 5a3ea500-918a-42e1-92eb-c33824df4ddc
                  name: 57a98d98e4b00679b4a830b2
                total: 18.99
        '406':
          description: Failed call with status 406
          content:
            application/json:
              example:
                error: Not Acceptable
                exception: works.weave.socks.orders.controllers.OrdersController$PaymentDeclinedException
                message: 'Payment declined: amount exceeds 100.00'
                path: "/orders"
                status: 406
                timestamp: 1655624563279
        '500':
          description: Failed call with status 500
          content:
            application/json:
              example:
                error: Internal Server Error
                exception: java.lang.IllegalStateException
                message: Unable to create order due to unspecified IO error.
                path: "/orders"
                status: 500
                timestamp: 1656763517623
      x-counters-per-source:
        front-end.sock-shop:
          entries: 2923993
          failures: 324640
          firstSeen: 1655624561
          lastSeen: 1656949151
          sumRT: 92022.1259999206
          sumDuration: 1382953
      x-counters-total:
        entries: 2923993
        failures: 324640
        firstSeen: 1655624561
        lastSeen: 1656949151
        sumRT: 92022.1259999206
        sumDuration: 1382953
      x-last-seen-ts: 1656949151
      requestBody:
        description: Generic request body
        content:
          application/json:
            example:
              address: http://user/addresses/57a98d98e4b00679b4a830b0
              card: http://user/cards/57a98d98e4b00679b4a830b1
              customer: http://user/customers/57a98d98e4b00679b4a830b2
              items: http://carts/carts/57a98d98e4b00679b4a830b2/items
        required: true
  "/orders/search/customerId":
    get:
      tags:
      - orders
      summary: "/orders/search/customerId"
      description: Mizu observed 9 entries (0 failed), at 8.444 hits/s, average response
        time is 11.539 seconds
      operationId: '092766ae-1b38-4660-862f-0f998c6405b9'
      parameters:
      - name: sort
        in: query
        required: true
        style: form
        schema:
          type: string
        examples:
          'example #0':
            value: date
      - name: custId
        in: query
        required: false
        style: form
        schema:
          type: string
        examples:
          'example #0':
            value: 62b4dba5758a340001cc36af
      responses:
        '200':
          description: Successful call with status 200
          content:
            application/hal+json:
              example:
                _embedded:
                  customerOrders: []
                _links:
                  self:
                    href: http://orders/orders/search/customerId?sort=date&custId=62b4dba5758a340001cc36af
      x-counters-per-source:
        front-end.sock-shop:
          entries: 9
          failures: 0
          firstSeen: 1656019883
          lastSeen: 1656019921
          sumRT: 103.85399999999998
          sumDuration: 76
      x-counters-total:
        entries: 9
        failures: 0
        firstSeen: 1656019883
        lastSeen: 1656019921
        sumRT: 103.85399999999998
        sumDuration: 76
      x-last-seen-ts: 1656019921
  "/orders/{orderId}":
    get:
      tags:
      - orders
      summary: "/orders/{orderId}"
      description: Mizu observed 3 entries (0 failed), at 0.000 hits/s, average response
        time is 0.304 seconds
      operationId: 1aa014d9-f011-4f5e-b4dc-8b073bcf9c34
      responses:
        '200':
          description: Successful call with status 200
          content:
            application/hal+json:
              example:
                _links:
                  order:
                    href: http://orders/orders/62b4dbd161c4e9000737fc02
                  self:
                    href: http://orders/orders/62b4dbd161c4e9000737fc02
                address:
                  city: Kubernetes
                  country: UP9
                  number: '1234'
                  postcode: '90210'
                  street: API Traffic viewer
                card:
                  ccv: '123'
                  expires: 12/26
                  longNum: '41111111111111111111'
                customer:
                  addresses: []
                  cards: []
                  firstName: Refael
                  lastName: "@ UP9"
                  username: Refael
                customerId: 62b4dba5758a340001cc36af
                date: '2022-06-23T21:32:01.072+0000'
                items:
                - itemId: 3395a43e-2d88-40de-b95f-e00e1502085b
                  quantity: 1
                  unitPrice: 18
                shipment:
                  name: 62b4dba5758a340001cc36af
                total: 22.99
      x-counters-per-source:
        front-end.sock-shop:
          entries: 3
          failures: 0
          firstSeen: 1656019924
          lastSeen: 1656019924
          sumRT: 0.9119999999999999
          sumDuration: 0
      x-counters-total:
        entries: 3
        failures: 0
        firstSeen: 1656019924
        lastSeen: 1656019924
        sumRT: 0.9119999999999999
        sumDuration: 0
      x-last-seen-ts: 1656019924
    parameters:
    - name: orderId
      in: path
      required: true
      style: simple
      schema:
        type: string
      examples:
        'example #0':
          value: 62b4dbd161c4e9000737fc02
x-counters-per-source:
  front-end.sock-shop:
    entries: 2924005
    failures: 324640
    firstSeen: 1655624561
    lastSeen: 1656949151
    sumRT: 92126.8919999206
    sumDuration: 1383029
x-counters-total:
  entries: 2924005
  failures: 324640
  firstSeen: 1655624561
  lastSeen: 1656949151
  sumRT: 92126.8919999206
  sumDuration: 1383029
components: {}
